# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dangnhap.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowdn(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(728, 485)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 421, 441))
        self.groupBox.setStyleSheet("border-image: url(:/bgr/360_F_460710131_YkD6NsivdyYsHupNvO3Y8MPEwxTAhORh.jpg);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(420, 0, 301, 441))
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(70, 90, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tb_tk = QtWidgets.QLineEdit(self.groupBox_2)
        self.tb_tk.setGeometry(QtCore.QRect(130, 150, 171, 31))
        self.tb_tk.setObjectName("tb_tk")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tb_mk = QtWidgets.QLineEdit(self.groupBox_2)
        self.tb_mk.setGeometry(QtCore.QRect(130, 200, 171, 31))
        self.tb_mk.setObjectName("tb_mk")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(100, 260, 121, 41))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 728, 21))
        self.menubar.setObjectName("menubar")
        self.menuCh_c_n_ng = QtWidgets.QMenu(self.menubar)
        self.menuCh_c_n_ng.setObjectName("menuCh_c_n_ng")
        self.menuTh_ng_k = QtWidgets.QMenu(self.menubar)
        self.menuTh_ng_k.setObjectName("menuTh_ng_k")
        self.menuTho_t = QtWidgets.QMenu(self.menubar)
        self.menuTho_t.setObjectName("menuTho_t")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQL_thu_cung = QtWidgets.QAction(MainWindow)
        self.actionQL_thu_cung.setObjectName("actionQL_thu_cung")
        self.actionQL_nhan_vien = QtWidgets.QAction(MainWindow)
        self.actionQL_nhan_vien.setObjectName("actionQL_nhan_vien")
        self.menuCh_c_n_ng.addSeparator()
        self.menuCh_c_n_ng.addAction(self.actionQL_thu_cung)
        self.menuCh_c_n_ng.addAction(self.actionQL_nhan_vien)
        self.menubar.addAction(self.menuCh_c_n_ng.menuAction())
        self.menubar.addAction(self.menuTh_ng_k.menuAction())
        self.menubar.addAction(self.menuTho_t.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Đăng nhập"))
        self.label.setText(_translate("MainWindow", "ĐĂNG NHẬP"))
        self.label_2.setText(_translate("MainWindow", "Tài khoản:"))
        self.label_3.setText(_translate("MainWindow", "Mật khẩu :"))
        self.pushButton.setText(_translate("MainWindow", "ĐĂNG NHẬP"))
        self.menuCh_c_n_ng.setTitle(_translate("MainWindow", "Chức năng"))
        self.menuTh_ng_k.setTitle(_translate("MainWindow", "Thống kê"))
        self.menuTho_t.setTitle(_translate("MainWindow", "Thoát"))
        self.actionQL_thu_cung.setText(_translate("MainWindow", "QL thu cung"))
        self.actionQL_nhan_vien.setText(_translate("MainWindow", "QL nhan vien"))
import bgr


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindowdn()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
