# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'QLTC')))
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'QLDH')))
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'QLDV')))
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'QLGTC')))
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'QLNV')))
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'QLTK')))
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'Thongke')))
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'TKNC')))

from QLTC import Ui_MainWindowtc
from QLDH import Ui_MainWindowdh
from QLDV import Ui_MainWindowdv
from QLGTC import Ui_QL_GTC
from QLNV import Ui_MainWindownv
from QLTK import Ui_MainWindowtk
from thongke import Ui_MainWindowtke
from tknc import Ui_MainWindowtknc


class Ui_MainWindow(object):
    def window(self,ui_main_window):
        window = QtWidgets.QMainWindow()
        ui = ui_main_window()
        ui.setupUi(window)
        return window
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1074, 696)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1074, 653))
        self.stackedWidget.setObjectName("stackedWidget")
        self.stackedWidget.addWidget(self.window(Ui_MainWindowdh))
        self.stackedWidget.addWidget(self.window(Ui_MainWindowdv))
        self.stackedWidget.addWidget(self.window(Ui_MainWindowtc))
        self.stackedWidget.addWidget(self.window(Ui_QL_GTC))
        self.stackedWidget.addWidget(self.window(Ui_MainWindownv))
        self.stackedWidget.addWidget(self.window(Ui_MainWindowtk))
        self.stackedWidget.addWidget(self.window(Ui_MainWindowtknc))
        self.stackedWidget.addWidget(self.window(Ui_MainWindowtke))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1074, 21))
        self.menubar.setObjectName("menubar")
        self.menuCh_c_n_ng = QtWidgets.QMenu(self.menubar)
        self.menuCh_c_n_ng.setObjectName("menuCh_c_n_ng")
        self.menuQL_thu_cung = QtWidgets.QMenu(self.menuCh_c_n_ng)
        self.menuQL_thu_cung.setObjectName("menuQL_thu_cung")
        self.menuTh_ng_k = QtWidgets.QMenu(self.menubar)
        self.menuTh_ng_k.setObjectName("menuTh_ng_k")
        self.menuTho_t = QtWidgets.QMenu(self.menubar)
        self.menuTho_t.setObjectName("menuTho_t")
        self.menuB_n_h_ng = QtWidgets.QMenu(self.menubar)
        self.menuB_n_h_ng.setObjectName("menuB_n_h_ng")
        self.menuTim_kiem = QtWidgets.QMenu(self.menubar)
        self.menuTim_kiem.setObjectName("menuTim_kiem")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQL_nhan_vien = QtWidgets.QAction(MainWindow)
        self.actionQL_nhan_vien.setObjectName("actionQL_nhan_vien")
        self.actionThu_cung = QtWidgets.QAction(MainWindow)
        self.actionThu_cung.setObjectName("actionThu_cung")
        self.actionGiong_thu_cung = QtWidgets.QAction(MainWindow)
        self.actionGiong_thu_cung.setObjectName("actionGiong_thu_cung")
        self.actionBan_thu_cung = QtWidgets.QAction(MainWindow)
        self.actionBan_thu_cung.setObjectName("actionBan_thu_cung")
        self.actionDich_vu = QtWidgets.QAction(MainWindow)
        self.actionDich_vu.setObjectName("actionDich_vu")
        self.actionQL_tai_khoan = QtWidgets.QAction(MainWindow)
        self.actionQL_tai_khoan.setObjectName("actionQL_tai_khoan")
        self.menuQL_thu_cung.addAction(self.actionThu_cung)
        self.menuQL_thu_cung.addAction(self.actionGiong_thu_cung)
        self.menuCh_c_n_ng.addAction(self.menuQL_thu_cung.menuAction())
        self.menuCh_c_n_ng.addAction(self.actionQL_nhan_vien)
        self.menuCh_c_n_ng.addAction(self.actionQL_tai_khoan)
        self.menuB_n_h_ng.addAction(self.actionBan_thu_cung)
        self.menuB_n_h_ng.addAction(self.actionDich_vu)
        self.menubar.addAction(self.menuB_n_h_ng.menuAction())
        self.menubar.addAction(self.menuCh_c_n_ng.menuAction())
        self.menubar.addAction(self.menuTim_kiem.menuAction())
        self.menubar.addAction(self.menuTh_ng_k.menuAction())
        self.menubar.addAction(self.menuTho_t.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuCh_c_n_ng.setTitle(_translate("MainWindow", "Quản lý"))
        self.menuQL_thu_cung.setTitle(_translate("MainWindow", "QL thu cung"))
        self.menuTh_ng_k.setTitle(_translate("MainWindow", "Thống kê"))
        self.menuTho_t.setTitle(_translate("MainWindow", "Thoát"))
        self.menuB_n_h_ng.setTitle(_translate("MainWindow", "Bán hàng"))
        self.menuTim_kiem.setTitle(_translate("MainWindow", "Tìm kiếm"))
        self.actionQL_nhan_vien.setText(_translate("MainWindow", "QL nhan vien"))
        self.actionThu_cung.setText(_translate("MainWindow", "Thu cung"))
        self.actionGiong_thu_cung.setText(_translate("MainWindow", "Giong thu cung"))
        self.actionBan_thu_cung.setText(_translate("MainWindow", "Ban thu cung"))
        self.actionDich_vu.setText(_translate("MainWindow", "Dich vu"))
        self.actionQL_tai_khoan.setText(_translate("MainWindow", "QL tai khoan"))
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
