# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QLDH.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog
import os
import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'SaveClass')))
from classtc import thucung
from classdh import donhang
from PyQt5.uic import loadUi

class Ui_MainWindowdh(QDialog):
    def __init__(self):
        super(Ui_MainWindowdh, self).__init__()
        loadUi("QLDH.ui",self)
        self.bt_ht.clicked.connect(self.hienthi)
        self.bt_tt.clicked.connect(self.thanhtoan)
        
    def hienthi(self):
        tc = thucung
        try:
            data = tc.timkiemma(self.tb_m.text())
            self.lb_m.setText(str(data[0][0]))
            self.lb_l.setText(str(data[0][1]))
            self.lb_g.setText(str(data[0][2]))
            self.lb_t.setText(str(data[0][3]))
            self.lb_gt.setText(str(data[0][4]))
            if(str(data[0][5]) == "True") :
                self.lb_tp.setText("Đã tiêm phòng")
            else:
                self.lb_tp.setText("Chưa tiêm phòng")
            self.lb_tt.setText(str(data[0][6]))
        except Exception as e:
            halo=QtWidgets.QMessageBox()
            halo.setInformativeText(f'Mã thú cưng không tồn tại')
            halo.exec()
    def thanhtoan(self):
        if(self.lb_m.text() != ""):
            matc = self.lb_m.text()
            cccd = self.tb_cccd.text()
            hoten = self.tb_ht.text()
            sdt = self.tb_sdt.text()
            dh = donhang(matc,cccd,hoten,sdt)
            dh.them()
            self.tb_m.clear()
            self.tb_cccd.clear()
            self.tb_ht.clear()
            self.tb_sdt.clear()
            self.lb_g.clear()
            self.lb_l.clear()
            self.lb_m.clear()
            self.lb_t.clear()
            self.lb_gt.clear()
            self.lb_tp.clear()
            self.lb_tt.clear()
        else:
            halo=QtWidgets.QMessageBox()
            halo.setInformativeText(f'Chưa nhấn hiển thị')
            halo.exec()
    